### ISSUE TITLE
sync.listen() should always start listening

### ISSUE THREAD

**Issue by gmaclennan** [digidem/mapeo-core#27]
In the (rare) case where you call sync.listen() while the swarm is being destroyed, then sync.listen() will not work, but will not return an error. https://github.com/digidem/mapeo-core/blob/master/sync.js#L146

Ideally I think sync.listen() should wait for the destroy to complete, and then start listening. This could be done by the API consumer, but it would be slightly complicated code to deal with.

**Comment by noffle** [comment]
Tracked now by https://github.com/digidem/mapeo-core/issues/82
