### ISSUE TITLE
peer state shouldn't be stored by peer.name

### ISSUE THREAD

**Issue by gmaclennan** [digidem/mapeo-core#31]
https://github.com/digidem/mapeo-core/blob/master/sync.js#L125 we do:

```js
this._state[peer.name] = peer
```

There are no guarantees that `peer.name` is unique (currently on mobile it is always the same) this will cause much weirdness. Should use `peer.id`? Is that guaranteed unique?

**Comment by karissa** [comment]
`peer.id` is different when the device reconnects, even though the name is the same.

**Comment by gmaclennan** [comment]
Other ideas? Currently this will break sync UI (but actual sync should be ok?) if two devices with the same name are on the same network.
