### ISSUE TITLE
Media setup "completing" before all media files are fully written

### ISSUE THREAD

**Issue by karissa** [digidem/mapeo-core#33]
why you so difficult, windows? https://travis-ci.org/digidem/mapeo-core/jobs/527532775#L228

**Comment by noffle** [comment]
I added some debug logging to the sync tests, and it looks like the helper that creates test images reports 'done!' before all of the media files have been written:

https://travis-ci.org/digidem/mapeo-core/jobs/539384181#L222

The above output shows that, by the time writing media data is "complete" there are still 2 images not present. However, by the time the test gets to syncing, it completes without errors. This leads me to conclude that the 2 missing media files got written in between media-writes-done and doing-sync. I think safe-fs-blob-store or one of the modules powered by it is calling its "done!" callback prematurely.

**Comment by noffle** [comment]
Just noticed that macOS also reports this sometimes: https://travis-ci.org/digidem/mapeo-core/jobs/542437935#L378
