### ISSUE TITLE
Use discovery key in sync files, not project key

### ISSUE THREAD

**Issue by gmaclennan** [digidem/mapeo-core#61]
Because the project key is sensitive (can be used to snoop on internet sync) I don't think we should include it in the sync files (I know a bit of a moot point because if someone has a sync file they can see all the data, but a project key also gives access to future data).

I think we should use the discovery key instead.

**Comment by noffle** [comment]
Where are we storing the project key in the syncfile?

**Comment by noffle** [comment]
Is this about how osm-p2p-syncfile stores a multifeed, which means it will contain a core that exposes the encryption key?

**Comment by noffle** [comment]
I think the easiest fix would actually be to have multifeed create its empty/fake hypercore *in memory* on startup, so then it's never written to disk anywhere.

**Comment by noffle** [comment]
Ok, done! Active in `multifeed@4.1.11`, which is a patch release, since nothing relied on the hypercore being on disk.

**Comment by gmaclennan** [comment]
ah yes, I hadn't thought about that. I was actually thinking about the projectKey that is being stored in the userdata in the sync file, but your right, it's in the fake hypercore too. Your fix looks good, and I think this makes a lot of sense and avoids leaking the project key when passing around these multifeeds for debugging etc.

**Comment by gmaclennan** [comment]
Fixed in #62
