### ISSUE TITLE
Sync does not end gracefully if not enough disk space

### ISSUE THREAD

**Issue by gmaclennan** [digidem/mapeo-core#73]
We've been seeing a few situations in the field where a full hard drive causes sync to fail or hang without an understandable error. There are 3 scenarios:

1. Device syncing over the network --> fills up disk space
2. Device creating a sync file --> not enough space for sync file
3. Device syncing _from_ an existing sync file --> can't write media and/or photos to kappa.db folder

Not sure how the error might be different if disk space is short for a hypercore write vs. a blob store write.

Ideally we could give a warning to the user _before_ sync starts e.g. "Not enough space to sync" because filling up the drive until nothing is left causes the computer to grind to a halt. If that's not possible then sync should fail gracefully and provide a clear error message with clear action for the user (e.g. "Remove some files from disk _C_ to free up some disk space")

**Comment by noffle** [comment]
One idea I had for debugging this is creating a small ramdisk locally:

```
sudo mount -t tmpfs -o size=2048M tmpfs my-ramdisk
```

And use it to locally simulate the 3 cases you outlined, to see how Node
and our stack reacts & whether errors get propagated.

**Comment by noffle** [comment]
I've started poking at this, and it's tricky. There are many places IO happens in Mapeo.

A node trick, which I think mapeo-desktop already uses is

```js
  process.on('uncaughtException', function (err) {
      console.trace('Caught exception:', err)
  })
```

which will catch all uncaught errors, like `ENOSPC`. I've been testing out different failure modes with a small local ramdisk, and sometimes get very unhelpful stack traces like

```
    at process._fatalException (bootstrap_node.js:375:26)
```

I'm plugging the easy holes as best I can, but a big catch-all might be necessary unless I can localize some of these stack traces better.

**Comment by noffle** [comment]
Places that I can confirm propagate `ENOSPC` or equivalent ok now on a full disk:

- `hypercore#append`
- blob store writes
- opening a leveldb
- leveldb writes
- `random-access-file#write`

This was all with a network peer -- I'll test some more with syncfiles too.

**Comment by noffle** [comment]
I've fixed some issues with syncfiles around out of disk errors in osm-p2p-syncfile, mapeo-core, and indexed-tarball.

**Comment by noffle** [comment]
I think we should be good for the vast majority of places I'd expect ENOSPC to crop up:

- [x] writing entries to syncfiles
- [x] extracting entries from syncfiles
- [x] writing blob entries to disk
- [x] writing hypercore entries to disk
