### ISSUE TITLE
Cannot assume that peer.name is unique

### ISSUE THREAD

**Issue by gmaclennan** [digidem/mapeo-core#83]
There are a couple of places in the sync code where `peer.name` is used as a lookup for a peer e.g.

- https://github.com/digidem/mapeo-core/blob/68de98d95d6612096272a1555bb8c603749c5a69/sync.js#L136
- https://github.com/digidem/mapeo-core/blob/68de98d95d6612096272a1555bb8c603749c5a69/sync.js#L145
- https://github.com/digidem/mapeo-core/blob/68de98d95d6612096272a1555bb8c603749c5a69/sync.js#L150

On mobile we (currently) randomly generate the name (but plan to change this in the future) but on Desktop we use the computer hostname as the name. I just realised that in the field it is quite common for computers to have identical hostnames (e.g. something like "Windows PC"), especially when multiple machines have been deployed at the same time. I think this would result in the completed states not being updated correctly.

**Comment by okdistribute** [comment]
Yes that's right.. originally I think this used peer.id, but we realized that ids don't persist between connections so this was a hack. The next version of mapeo-core uses `peer.id`, since they persist between connections.

**Comment by noffle** [comment]
Agreed that using `name` is problematic.

What level of consistency is desired?

1. consistent across reconnects (session-wide)
2. consistent across sessions (permanent to the device)

If the former, a random ID at startup is fine. If the latter, we could use a hash of the device's writeable hypercore public key.

**Comment by gmaclennan** [comment]
I think (2) - permanent to device, because during the process of sync a user might close the mobile app and return to it, or quit and re-open the desktop app, so if it errored then a reconnect after app restart should be able to link to the same peer

**Comment by noffle** [comment]
This will be fixed by #87.
